const PLATFORMS = {
  // ═══ UNITED STATES ═══
  recreation_gov: {
    name: "Recreation.gov",
    country: "US",
    bookingWindowTime: "10:00",
    bookingWindowTimezone: "America/New_York",
    advanceBookingDays: 180,
    deepLinkTemplate: "https://www.recreation.gov/camping/campgrounds/{campgroundId}",
    searchUrl: "https://www.recreation.gov/search",
    cartTimeoutMinutes: 15,
    hasPublicApi: true,
    popularCampgrounds: [
      { id: "232447", name: "Upper Pines", park: "Yosemite", state: "CA" },
      { id: "232450", name: "Lower Pines", park: "Yosemite", state: "CA" },
      { id: "232449", name: "North Pines", park: "Yosemite", state: "CA" },
      { id: "232448", name: "Wawona", park: "Yosemite", state: "CA" },
      { id: "232452", name: "Hodgdon Meadow", park: "Yosemite", state: "CA" },
      { id: "251869", name: "Jumbo Rocks", park: "Joshua Tree", state: "CA" },
      { id: "251870", name: "Black Rock", park: "Joshua Tree", state: "CA" },
      { id: "232473", name: "Watchman", park: "Zion", state: "UT" },
      { id: "232493", name: "Mather", park: "Grand Canyon South Rim", state: "AZ" },
      { id: "10083745", name: "Seawall", park: "Acadia", state: "ME" },
      { id: "232770", name: "Moraine Park", park: "Rocky Mountain", state: "CO" },
      { id: "232769", name: "Glacier Basin", park: "Rocky Mountain", state: "CO" },
      { id: "10103767", name: "Platte River", park: "Sleeping Bear Dunes", state: "MI" },
      { id: "232468", name: "Kalaloch", park: "Olympic", state: "WA" },
      { id: "247592", name: "Pinnacles", park: "Pinnacles", state: "CA" },
    ]
  },
  reserve_california: {
    name: "Reserve California",
    country: "US",
    bookingWindowTime: "08:00",
    bookingWindowTimezone: "America/Los_Angeles",
    advanceBookingDays: 180,
    deepLinkTemplate: "https://www.reservecalifornia.com/Web/#702/{campgroundId}",
    searchUrl: "https://www.reservecalifornia.com",
    cartTimeoutMinutes: 15,
    hasPublicApi: false,
    popularCampgrounds: [
      { id: "720", name: "Big Basin Redwoods SP", state: "CA" },
      { id: "682", name: "Julia Pfeiffer Burns SP", state: "CA" },
      { id: "738", name: "Pfeiffer Big Sur SP", state: "CA" },
      { id: "643", name: "Doran Regional Park", state: "CA" },
      { id: "658", name: "Half Moon Bay SB", state: "CA" },
      { id: "698", name: "MacKerricher SP", state: "CA" },
      { id: "601", name: "Anza-Borrego Desert SP", state: "CA" },
      { id: "673", name: "Jedediah Smith Redwoods SP", state: "CA" },
      { id: "737", name: "New Brighton SB", state: "CA" },
      { id: "634", name: "Crystal Cove SP", state: "CA" },
    ]
  },
  reserve_america: {
    name: "ReserveAmerica",
    country: "US",
    bookingWindowTime: "varies",
    bookingWindowTimezone: "varies",
    advanceBookingDays: 180,
    deepLinkTemplate: "https://www.reserveamerica.com/explore/campground/{campgroundId}",
    searchUrl: "https://www.reserveamerica.com",
    cartTimeoutMinutes: 15,
    hasPublicApi: false,
    states: ["NY", "NH", "ME", "CT", "GA", "VA", "WV", "SC", "LA", "MS", "AL", "MD", "NJ", "RI", "VT"],
    popularCampgrounds: [
      { id: "ny-north-south-lake", name: "North-South Lake", state: "NY" },
      { id: "ny-letchworth", name: "Letchworth SP", state: "NY" },
      { id: "nh-franconia-notch", name: "Franconia Notch SP", state: "NH" },
      { id: "me-baxter", name: "Baxter SP", state: "ME" },
      { id: "ga-fort-mountain", name: "Fort Mountain SP", state: "GA" },
      { id: "va-shenandoah", name: "Shenandoah River SP", state: "VA" },
    ]
  },

  // ═══ CANADA ═══
  parks_canada: {
    name: "Parks Canada",
    country: "CA",
    bookingWindowTime: "08:00",
    bookingWindowTimezone: "America/Toronto",
    advanceBookingDays: 152, // Opens in January for the full season
    deepLinkTemplate: "https://reservation.pc.gc.ca/{parkSlug}/{campgroundSlug}",
    searchUrl: "https://reservation.pc.gc.ca",
    cartTimeoutMinutes: 15,
    hasPublicApi: false,
    apiEndpoint: "https://reservation.pc.gc.ca/ResInfo.ashx",
    notes: "Opens all at once in January. Block release, not rolling.",
    popularCampgrounds: [
      { id: "BrucePeninsula/CyprusLake", name: "Cyprus Lake", park: "Bruce Peninsula", province: "ON" },
      { id: "PacificRimNPR/GreenPoint", name: "Green Point", park: "Pacific Rim", province: "BC" },
      { id: "Banff/TwoJack", name: "Two Jack Lakeside", park: "Banff", province: "AB" },
      { id: "Banff/JohnstonCanyon", name: "Johnston Canyon", park: "Banff", province: "AB" },
      { id: "Banff/TunnelMountain1", name: "Tunnel Mountain Village I", park: "Banff", province: "AB" },
      { id: "Jasper/Wapiti", name: "Wapiti", park: "Jasper", province: "AB" },
      { id: "Jasper/Whistlers", name: "Whistlers", park: "Jasper", province: "AB" },
      { id: "WatertonLakes/Townsite", name: "Townsite", park: "Waterton Lakes", province: "AB" },
      { id: "PEI/Cavendish", name: "Cavendish", park: "PEI National Park", province: "PE" },
      { id: "GrosMorne/BerryHill", name: "Berry Hill", park: "Gros Morne", province: "NL" },
      { id: "FundyNP/Headquarters", name: "Headquarters", park: "Fundy", province: "NB" },
      { id: "KejimkujikNP/JeremysBay", name: "Jeremy's Bay", park: "Kejimkujik", province: "NS" },
      { id: "Kootenay/Redstreak", name: "Redstreak", park: "Kootenay", province: "BC" },
      { id: "GlacierNP/IllecillewaetGreenslide", name: "Illecillewaet", park: "Glacier", province: "BC" },
      { id: "RidingMountain/Wasagaming", name: "Wasagaming", park: "Riding Mountain", province: "MB" },
    ]
  },
  bc_parks: {
    name: "BC Parks (Discover Camping)",
    country: "CA",
    bookingWindowTime: "07:00",
    bookingWindowTimezone: "America/Vancouver",
    advanceBookingDays: 120,
    deepLinkTemplate: "https://camping.bcparks.ca/create-booking/results?resourceLocationId={locationId}",
    searchUrl: "https://camping.bcparks.ca",
    cartTimeoutMinutes: 15,
    hasPublicApi: false,
    popularCampgrounds: [
      { id: "-2504", name: "Rathtrevor Beach", province: "BC" },
      { id: "-2493", name: "Golden Ears - Alouette", province: "BC" },
      { id: "-2471", name: "Cultus Lake", province: "BC" },
      { id: "-2443", name: "Birkenhead Lake", province: "BC" },
      { id: "-2532", name: "Shuswap Lake", province: "BC" },
      { id: "-2457", name: "Englishman River Falls", province: "BC" },
      { id: "-2499", name: "Joffre Lakes", province: "BC" },
      { id: "-2472", name: "Cypress Provincial Park", province: "BC" },
      { id: "-2503", name: "Porteau Cove", province: "BC" },
      { id: "-2430", name: "Alice Lake", province: "BC" },
      { id: "-2521", name: "Okanagan Lake South", province: "BC" },
      { id: "-2497", name: "Haynes Point", province: "BC" },
    ]
  },
  ontario_parks: {
    name: "Ontario Parks",
    country: "CA",
    bookingWindowTime: "07:00",
    bookingWindowTimezone: "America/Toronto",
    advanceBookingDays: 150, // 5 months ahead
    deepLinkTemplate: "https://reservations.ontarioparks.ca/create-booking/results?resourceLocationId={locationId}",
    searchUrl: "https://reservations.ontarioparks.ca",
    cartTimeoutMinutes: 15,
    hasPublicApi: false,
    popularCampgrounds: [
      { id: "-2740399", name: "Algonquin - Canisbay Lake", park: "Algonquin", province: "ON" },
      { id: "-2740407", name: "Algonquin - Pog Lake", park: "Algonquin", province: "ON" },
      { id: "-2740393", name: "Algonquin - Lake of Two Rivers", park: "Algonquin", province: "ON" },
      { id: "-2740523", name: "Killarney - George Lake", park: "Killarney", province: "ON" },
      { id: "-2740285", name: "Sandbanks - Outlet River", park: "Sandbanks", province: "ON" },
      { id: "-2740575", name: "Pinery - Burley", park: "Pinery", province: "ON" },
      { id: "-2740387", name: "Bon Echo - Mazinaw Lake", park: "Bon Echo", province: "ON" },
      { id: "-2740451", name: "Grundy Lake", park: "Grundy Lake", province: "ON" },
      { id: "-2740611", name: "Silent Lake", park: "Silent Lake", province: "ON" },
      { id: "-2740303", name: "Arrowhead", park: "Arrowhead", province: "ON" },
    ]
  },
  alberta_parks: {
    name: "Alberta Parks",
    country: "CA",
    bookingWindowTime: "09:00",
    bookingWindowTimezone: "America/Edmonton",
    advanceBookingDays: 90,
    deepLinkTemplate: "https://reserve.albertaparks.ca/create-booking/results?resourceLocationId={locationId}",
    searchUrl: "https://reserve.albertaparks.ca",
    cartTimeoutMinutes: 15,
    hasPublicApi: false,
    popularCampgrounds: [
      { id: "ab-bow-valley", name: "Bow Valley", park: "Bow Valley", province: "AB" },
      { id: "ab-peter-lougheed-boulton", name: "Boulton Creek", park: "Peter Lougheed", province: "AB" },
      { id: "ab-peter-lougheed-elkwood", name: "Elkwood", park: "Peter Lougheed", province: "AB" },
      { id: "ab-william-watson", name: "William Watson Lodge", park: "Peter Lougheed", province: "AB" },
      { id: "ab-writing-on-stone", name: "Writing-on-Stone", park: "Writing-on-Stone", province: "AB" },
      { id: "ab-dinosaur", name: "Dinosaur", park: "Dinosaur Provincial", province: "AB" },
      { id: "ab-crimson-lake", name: "Crimson Lake", park: "Crimson Lake", province: "AB" },
      { id: "ab-cypress-hills", name: "Elkwater", park: "Cypress Hills", province: "AB" },
    ]
  },
  sepaq: {
    name: "SEPAQ (Quebec)",
    country: "CA",
    bookingWindowTime: "09:00",
    bookingWindowTimezone: "America/Toronto",
    advanceBookingDays: 120,
    deepLinkTemplate: "https://www.sepaq.com/en/reservation/camping/{parkSlug}",
    searchUrl: "https://www.sepaq.com/en/reservation/camping",
    cartTimeoutMinutes: 15,
    hasPublicApi: false,
    popularCampgrounds: [
      { id: "mont-tremblant", name: "La Diable", park: "Mont-Tremblant", province: "QC" },
      { id: "jacques-cartier", name: "Les Alluvions", park: "Jacques-Cartier", province: "QC" },
      { id: "oka", name: "Oka", park: "Oka", province: "QC" },
      { id: "mauricie", name: "Wapizagonke", park: "La Mauricie", province: "QC" },
      { id: "grands-jardins", name: "Grands-Jardins", park: "Grands-Jardins", province: "QC" },
      { id: "bic", name: "Bic", park: "Bic", province: "QC" },
    ]
  },
  manitoba_parks: {
    name: "Manitoba Parks",
    country: "CA",
    bookingWindowTime: "07:00",
    bookingWindowTimezone: "America/Winnipeg",
    advanceBookingDays: 90,
    deepLinkTemplate: "https://prsp.gov.mb.ca/park/{parkSlug}",
    searchUrl: "https://prsp.gov.mb.ca",
    cartTimeoutMinutes: 15,
    hasPublicApi: false,
    popularCampgrounds: [
      { id: "whiteshell-west-hawk", name: "West Hawk Lake", park: "Whiteshell", province: "MB" },
      { id: "whiteshell-falcon", name: "Falcon Lake", park: "Whiteshell", province: "MB" },
      { id: "birds-hill", name: "Birds Hill", park: "Birds Hill", province: "MB" },
      { id: "spruce-woods", name: "Kiche Manitou", park: "Spruce Woods", province: "MB" },
    ]
  },
  saskatchewan_parks: {
    name: "Saskatchewan Parks",
    country: "CA",
    bookingWindowTime: "07:00",
    bookingWindowTimezone: "America/Regina",
    advanceBookingDays: 90,
    deepLinkTemplate: "https://camping.saskparks.com",
    searchUrl: "https://camping.saskparks.com",
    cartTimeoutMinutes: 15,
    hasPublicApi: false,
    popularCampgrounds: [
      { id: "prince-albert-main", name: "Main Campground", park: "Prince Albert", province: "SK" },
      { id: "cypress-hills-centre", name: "Centre Block", park: "Cypress Hills", province: "SK" },
      { id: "duck-mountain", name: "Duck Mountain", park: "Duck Mountain", province: "SK" },
    ]
  },
};
